spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Active la découverte automatique des routes pour les services enregistrés
      routes:            # Routes statiques (facultatif si vous voulez combiner avec la découverte dynamique)
        - id: r1
          uri: http://localhost:8080/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**