spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # Allow CORS for all routes
            allowedOrigins: "http://localhost:3000"  # Allow requests from my frontend app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE